# Generated by Django 4.1.7 on 2023-04-13 12:51

from django.db import migrations, models
import django.db.models.deletion
import my_store_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('customers_sellers', '0003_shop'),
        ('goods', '0003_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, verbose_name='Название товара')),
                ('description', models.TextField(blank=True, verbose_name='Описание товара')),
                ('purchase_count', models.IntegerField(default=0, verbose_name='счетчик покупок данного товара')),
                ('product_seen', models.IntegerField(default=0, verbose_name='счетчик просмотров данного товара')),
                ('slug', models.SlugField(help_text='Не рекомендуется изменять это поле самостоятельно.', max_length=150, unique=True, verbose_name='Название товара на латинице')),
                ('is_active', models.BooleanField(default=False, verbose_name='Готов к продажам')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_products', to='goods.categoryproduct', verbose_name='Категория товара')),
                ('customers', models.ManyToManyField(to='customers_sellers.customer', verbose_name='Покупатели', null=True, blank=True)),
                ('title_picture', models.ImageField(blank=True, upload_to=my_store_app.utils.GetUploadPath.get_upload_path_for_title_product_image, verbose_name='Титульное изображение')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='ProductShopRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество товара')),
                ('free_delivery', models.BooleanField(default=False, verbose_name='Бесплатная доставка')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='goods.product', verbose_name='Товар')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_products', to='customers_sellers.shop', verbose_name='Магазин')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shops',
            field=models.ManyToManyField(through='goods.ProductShopRelations', to='customers_sellers.shop', verbose_name='Магазины'),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sp_products', to='goods.specifications', verbose_name='Спецификация товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='products_tag', to='goods.tags', verbose_name='Тэги'),
        ),
    ]
