# Generated by Django 4.1.7 on 2023-04-18 05:13

from django.db import migrations, models
import django.db.models.deletion
import my_store_app.utils


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_productshoprelations_product_shops_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=my_store_app.utils.GetUploadPath.get_upload_path_for_product_images, verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='goods.product', verbose_name='Товар')),
            ],
        ),
    ]
