# Generated by Django 4.1.7 on 2023-04-13 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
                ('page', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('http_method', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=255, unique=True)),
                ('comment', models.TextField(default='--')),
            ],
        ),
    ]
