# Generated by Django 4.1.7 on 2023-05-15 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('family_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('phone', models.CharField(max_length=30, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='email пользователя')),
                ('delivery_method', models.CharField(blank=True, max_length=100, verbose_name='Способ доставки', choices=[('common', 'Обычная доставка'), ('express', 'Экспресс-доставка')])),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город доставки')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес доставки')),
                ('pay_method', models.CharField(blank=True, max_length=100, verbose_name='Метод оплаты', choices=[('online_card', 'Онлайн картой'), ('random_check', 'Онлайн со случайного чужого счета')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Активный пользователь', related_name='order', blank=True, null=True, help_text='Пользователь, на котором в данный момент закреплён заказ')),
                ('comment', models.CharField(blank=True, max_length=350, verbose_name='Комментарий к заказу')),
                ('status', models.CharField(choices=[('not_paid', 'Не оплачено'), ('paid', 'Оплачен'), ('error', 'Ошибка')], max_length=100, verbose_name='Статус заказа')),
                ('delivery_price', models.SmallIntegerField(default=0, verbose_name='Сумма на доставку')),
                ('error_message', models.CharField(blank=True, max_length=250, verbose_name='Описание ошибки оплаты')),
                ('history_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_order', to=settings.AUTH_USER_MODEL, verbose_name='Архивный пользователь')),
                ('payment_date', models.DateTimeField(blank=True, verbose_name='Дата оплаты заказа')),
                ('basket_objects', models.ManyToManyField(blank=True, related_name='order', to='cart.basket', verbose_name='Корзина заказа')),
                ('archived', models.BooleanField(default=False, verbose_name='Архивированно/Заказ выполнен')),
            ],
        ),
    ]
