# Generated by Django 4.1.7 on 2023-04-13 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import my_store_app.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя не указано', help_text='Необязательно', max_length=50, verbose_name='Имя')),
                ('family_name', models.CharField(default='Фамилия не указана', help_text='Необязательно', max_length=50, verbose_name='Фамилия')),
                ('surname', models.CharField(default='Отчество не указано', help_text='Необязательно', max_length=50, verbose_name='Отчество')),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email пользователя')),
                ('avatar', models.ImageField(blank=True, help_text='Необязательно.', upload_to=my_store_app.utils.GetUploadPath.get_upload_path_for_user_avatar, validators=[my_store_app.utils.validate_image])),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
