# Generated by Django 4.1.7 on 2023-04-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_product_productshoprelations_product_shops_and_more'),
        ('customers_sellers', '0003_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(to='goods.product', verbose_name='Продукты', blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='products',
            field=models.ManyToManyField(through='goods.ProductShopRelations', to='goods.product', verbose_name='Продукты'),
        ),
    ]
