# Generated by Django 4.1.7 on 2023-04-14 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers_sellers', '0004_customer_products_shop_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop_info', to='customers_sellers.shop', verbose_name='Магазин')),
                ('shop_name', models.CharField(max_length=250, verbose_name='Название магазина')),
                ('address', models.CharField(max_length=250, unique=True, verbose_name='Адрес магазина')),
                ('owner_name', models.CharField(default='Имя владельца не указано', help_text='Необязательно', max_length=50, verbose_name='Имя владельца')),
                ('owner_family_name', models.CharField(default='Фамилия владельца не указана', help_text='Необязательно', max_length=50, verbose_name='Фамилия владельца')),
                ('owner_surname', models.CharField(default='Отчество владельца не указано', help_text='Необязательно', max_length=50, verbose_name='Отчество владельца')),
            ],
        ),
    ]
