# Generated by Django 4.1.7 on 2023-04-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers_sellers', '0005_shopinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Покупатель', 'verbose_name_plural': 'Покупатели'},
        ),
        migrations.AlterModelOptions(
            name='shop',
            options={'verbose_name': 'Магазин', 'verbose_name_plural': 'Магазины'},
        ),
        migrations.AlterModelOptions(
            name='shopinfo',
            options={'verbose_name': 'Информация о магазине', 'verbose_name_plural': 'Информация о магазинах'},
        ),
    ]
